const products = {
    phones: [
        { 
            no: 1, 
            brand: 'Tomato',
            series: 'iPhone', 
            model: '542S pro max biturbo gtr', 
            price: 50000, 
            inStore: 1532, 
        },
        { 
            no: 2, 
            brand: 'Samsung', 
            series: 'Galaxy', 
            model: 'Skyline Avada Kedavra s8923', 
            price: 75000, 
            inStore: 45,
        },
        { 
            no: 3, 
            brand: 'Meizu',
            series: '103RX', 
            model: 'China power 3d imax', 
            price: 44500, 
            inStore: 35,
        },
        { 
            no: 4, 
            brand: 'Motorolla',
            series: 'B', 
            model: 'Rose Gold (994657)',  
            price: 5400,
            inStore: 123,
        },
        { 
            no: 5, 
            brand: 'ZTE',
            series: 'Blade', 
            model: 'W24',  
            price: 200, 
            inStore: 142345,
        },
    ],
    laptops: [
        { 
            no: 1, 
            brand: 'Acer',
            series: 'Aspire 5', 
            model: 'A515-56G-51Q5', 
            price: 22000, 
            inStore: 54, 
        },
        { 
            no: 2, 
            brand: 'Asus', 
            series: 'TUF', 
            model: 'Dash F15 FX517ZC', 
            price: 39999, 
            inStore: 32,
        },
        { 
            no: 3, 
            brand: 'Apple',
            series: 'MacBook Air 13', 
            model: 'M1 8/256GB 2020', 
            price: 44000, 
            inStore: 12,
        },
        { 
            no: 4, 
            brand: 'Durabook',
            series: 'X12', 
            model: 'Z4E2C3',  
            price: 274049,
            inStore: 1,
        },
        { 
            no: 5, 
            brand: 'MSI',
            series: 'Titan', 
            model: 'GT77 12UHS-006',  
            price: 270000, 
            inStore: 1,
        },
    ],
    monitors: [
        { 
            no: 1, 
            brand: 'HP',
            series: 'X', 
            model: '23.6" X24c 9FMM22A', 
            price: 5499, 
            inStore: 53, 
        },
        { 
            no: 2, 
            brand: 'Samsung', 
            series: 'Curved', 
            model: '23.5" LS24C366', 
            price: 4599, 
            inStore: 25,
        },
        { 
            no: 3, 
            brand: 'Dell',
            series: 'G', 
            model: '31.5" G3223D', 
            price: 17999, 
            inStore: 20,
        },
        { 
            no: 4, 
            brand: 'MSI',
            series: 'Optix', 
            model: '37.5" MEG381CQR',  
            price: 94067,
            inStore: 5,
        },
        { 
            no: 5, 
            brand: 'Asus',
            series: 'ROG', 
            model: '47.5" Swift PG48UQ UHD',  
            price: 93248, 
            inStore: 4,
        },
    ],
    printers: [
        { 
            no: 1, 
            brand: 'Canon',
            series: 'Pixma', 
            model: 'Ink Efficency E414', 
            price: 2999, 
            inStore: 32, 
        },
        { 
            no: 2, 
            brand: 'HP', 
            series: 'Laser', 
            model: '107WR', 
            price: 6999, 
            inStore: 15,
        },
        { 
            no: 3, 
            brand: 'Xerox',
            series: 'VersaLink', 
            model: 'c800w White', 
            price: 248220, 
            inStore: 4,
        },
        { 
            no: 4, 
            brand: 'OKI',
            series: 'MC', 
            model: 'MC883DN',  
            price: 139369,
            inStore: 7,
        },
        { 
            no: 5, 
            brand: 'Kyocera',
            series: 'ecosys', 
            model: 'MA5500ifx',  
            price: 64969, 
            inStore: 15,
        },
    ],
    routers: [
        { 
            no: 1, 
            brand: 'TP-LINK',
            series: 'Archer', 
            model: 'C64', 
            price: 1399, 
            inStore: 43, 
        },
        { 
            no: 2, 
            brand: 'Tenda', 
            series: 'AC', 
            model: 'AC10', 
            price: 749, 
            inStore: 94,
        },
        { 
            no: 3, 
            brand: 'Mercusys',
            series: 'MW', 
            model: 'MW301R', 
            price: 449, 
            inStore: 124,
        },
        { 
            no: 4, 
            brand: 'Xiaomi',
            series: 'Mi Router', 
            model: 'AX9000',  
            price: 7919,
            inStore: 22,
        },
        { 
            no: 5, 
            brand: 'MicroTik',
            series: 'ccr', 
            model: 'ccr2216-qg',  
            price: 102082, 
            inStore: 2,
        },
    ],
  };