const cities = {
  na: 'Not available',
  kie: 'Kyiv',
  ods: 'Odesa',
  chk: 'Cherkasy',
  chr: 'Chernygiv',
  chn: 'Chernivtsy',
  vin: 'Vinnytsa',
  dni: 'Dnipro',
  don: 'Donetsk',
  zap: 'Zaporizhya',
  zhi: 'Zhitomyr',
  ivf: 'Ivano-Frankivsk',
  izm: 'Izmail',
  kha: 'Kharkiv',
  khe: 'Kherson',
  khm: 'Khmelnytsky',
  kro: 'Kropivnytsky',
  luh: 'Luhansk',
  lut: 'Lutsk',
  lvi: 'Lviv',
  myk: 'Mykolaiv',
  pol: 'Poltava',
  riv: 'Rivne',
  sev: 'Sevastopol',
  sum: 'Summy',
  uzh: 'Uzhgorod',
};